name: Run Windows tests

on:
  # This avoids having duplicate builds for a pull request
  push:
    branches:
    - master
    - 5.x
    - 4.x
  pull_request:
    branches:
    - master
    - 5.x
    - 4.x

jobs:
  build:
    name: (Conda:${{ matrix.USE_CONDA }}, Py${{ matrix.PYTHON_VERSION }}, ${{ matrix.RUN_SLOW }})
    runs-on: windows-latest
    env:
      CI: True
      CODECOV_TOKEN: "56731c25-9b1f-4340-8b58-35739bfbc52d"
      CONDA_EXE: "C:\\Miniconda\\condabin\\conda.bat"
      PYTHON: "C:\\Miniconda"
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      RUN_SLOW: ${{ matrix.RUN_SLOW }}
      USE_CONDA: ${{ matrix.USE_CONDA }}
    strategy:
      fail-fast: false 
      matrix:
        USE_CONDA: ['yes']
        PYTHON_VERSION: ['3.7']
        RUN_SLOW: ['slow', 'fast']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1.2.0
      - name: Cache pip
        uses: actions/cache@v1
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Add Conda to PATH
        shell: python
        run: |
          print("::add-path::{}".format("C:\\Miniconda\\condabin"))
          print("::add-path::{}".format("C:\\Miniconda\\Scripts"))
      - name: Set up Conda
        shell: cmd
        run: >-
          conda config --set always_yes yes --set changeps1 no &&
          conda config --add pkgs_dirs ~\AppData\Local\conda\Cache &&
          conda install conda=4.7 -q
      - name: Conda info
        shell: cmd
        run: >-
          "%CONDA_EXE%" activate base &&
          conda info &&
          conda list &&
      - name: Create test environment
        shell: cmd
        run: >-
          "%CONDA_EXE%" activate base &&
          conda create -n test python=%PYTHON_VERSION% &&
          "%CONDA_EXE%" activate test &&
          continuous_integration\github\install.bat &&
      - name: Show test environment
        shell: cmd
        run: >-
          "%CONDA_EXE%" activate test &&
          conda info &&
          conda list &&
      - name: Run tests
        shell: cmd
        run: >-
          "%CONDA_EXE%" activate test &&
          where python &&
          where pip &&
          continuous_integration\github\runtests.bat
      - name: Coverage
        shell: cmd
        run: >-
          "%CONDA_EXE%" activate test &&
          codecov
